"""Entity Relationship One to Many product to materials 

Revision ID: 04fa5aa3f2f1
Revises: e94d64ba4ee5
Create Date: 2024-06-08 22:55:08.558727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04fa5aa3f2f1'
down_revision = 'e94d64ba4ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'product_list', ['fk_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_product_id')

    # ### end Alembic commands ###
