"""empty message

Revision ID: 18e464a1e8c3
Revises: 78ec53e07a65
Create Date: 2024-06-12 20:12:15.423522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18e464a1e8c3'
down_revision = '78ec53e07a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usable', sa.Boolean(), nullable=True))
        batch_op.drop_column('valid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('usable')

    # ### end Alembic commands ###
