"""empty message

Revision ID: 27e1193b66a0
Revises: 585f7a0b329c
Create Date: 2024-06-08 13:11:38.234245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e1193b66a0'
down_revision = '585f7a0b329c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
