"""empty message

Revision ID: 2ae2c14b18ed
Revises: 739e81ec3964
Create Date: 2024-06-11 09:44:44.395717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae2c14b18ed'
down_revision = '739e81ec3964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    with op.batch_alter_table('material_list', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
