"""empty message

Revision ID: 6218d5611a9b
Revises: bf6789ada840
Create Date: 2024-06-11 12:48:42.126179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6218d5611a9b'
down_revision = 'bf6789ada840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('modified_by')

    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.drop_column('modified_by')

    with op.batch_alter_table('material_list', schema=None) as batch_op:
        batch_op.drop_column('modified_by')

    # ### end Alembic commands ###
