"""empty message

Revision ID: 67f5f6a16461
Revises: c27a43136209
Create Date: 2024-06-09 11:48:08.461863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f5f6a16461'
down_revision = 'c27a43136209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material', schema=None) as batch_op:
        batch_op.drop_constraint('product_id_cons', type_='foreignkey')
        batch_op.drop_constraint('material_id_cons', type_='foreignkey')
        batch_op.create_foreign_key(None, 'material_list', ['material_id'], ['id'])
        batch_op.create_foreign_key(None, 'product_list', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('material_id_cons', 'material_list', ['material_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('product_id_cons', 'product_list', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
