"""empty message

Revision ID: 68ce7e108128
Revises: 67f5f6a16461
Create Date: 2024-06-09 11:57:39.226916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ce7e108128'
down_revision = '67f5f6a16461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_qty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material', schema=None) as batch_op:
        batch_op.drop_column('material_qty')

    # ### end Alembic commands ###
