"""empty message

Revision ID: 739e81ec3964
Revises: 516533c4b603
Create Date: 2024-06-10 17:56:17.673537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '739e81ec3964'
down_revision = '516533c4b603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', mysql.VARCHAR(length=300), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
