"""empty message

Revision ID: 78ec53e07a65
Revises: c404be9fb0af
Create Date: 2024-06-12 19:05:00.816251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78ec53e07a65'
down_revision = 'c404be9fb0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_location_code', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('storage_location_name', sa.String(length=300), nullable=False))
        batch_op.drop_index('storage_loc_code')
        batch_op.create_unique_constraint(None, ['storage_location_code'])
        batch_op.drop_column('storage_loc_code')
        batch_op.drop_column('storage_loc_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_loc_name', mysql.VARCHAR(length=300), nullable=False))
        batch_op.add_column(sa.Column('storage_loc_code', mysql.VARCHAR(length=30), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('storage_loc_code', ['storage_loc_code'], unique=True)
        batch_op.drop_column('storage_location_name')
        batch_op.drop_column('storage_location_code')

    # ### end Alembic commands ###
