"""add consumable column

Revision ID: 7b7103ce161b
Revises: 93f281ab7552
Create Date: 2024-06-08 07:19:04.660578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b7103ce161b'
down_revision = '93f281ab7552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material_list', schema=None) as batch_op:
        batch_op.drop_column('consumable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
