"""empty message

Revision ID: 982223ba6aa3
Revises: 94c34112cdc4
Create Date: 2024-06-11 18:32:27.703532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982223ba6aa3'
down_revision = '94c34112cdc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_code', sa.String(length=30), nullable=False),
    sa.Column('access_name', sa.String(length=300), nullable=False),
    sa.Column('access_desc', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_right', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('access_right')

    op.drop_table('access_right')
    # ### end Alembic commands ###
