"""empty message

Revision ID: 9f7db7201559
Revises: 68ce7e108128
Create Date: 2024-06-09 11:58:46.160006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f7db7201559'
down_revision = '68ce7e108128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_material_qty', sa.Integer(), nullable=True))
        batch_op.drop_column('material_qty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('used_material_qty')

    # ### end Alembic commands ###
