"""New Table: product_list

Revision ID: a8e3dbc65b9b
Revises: 2ac69bfbab8a
Create Date: 2024-06-08 10:38:15.574379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e3dbc65b9b'
down_revision = '2ac69bfbab8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(length=5), nullable=False),
    sa.Column('consumable', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_list')
    # ### end Alembic commands ###
