"""empty message

Revision ID: c27a43136209
Revises: 04fa5aa3f2f1
Create Date: 2024-06-09 11:29:43.208537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c27a43136209'
down_revision = '04fa5aa3f2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(length=200), nullable=False),
    sa.Column('consumable', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('fk_product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_product_id'], ['product_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    with op.batch_alter_table('product_material_list', schema=None) as batch_op:
        batch_op.drop_index('barcode')

    op.drop_table('product_material_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_material_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('barcode', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('qty', mysql.FLOAT(), nullable=True),
    sa.Column('uom', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('consumable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('image', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('fk_product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_product_id'], ['product_list.id'], name='product_material_list_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_product_id'], ['product_list.id'], name='product_material_list_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('product_material_list', schema=None) as batch_op:
        batch_op.create_index('barcode', ['barcode'], unique=True)

    op.drop_table('material_list')
    # ### end Alembic commands ###
