"""empty message

Revision ID: c404be9fb0af
Revises: 982223ba6aa3
Create Date: 2024-06-12 19:02:03.006542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c404be9fb0af'
down_revision = '982223ba6aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_location', sa.String(length=200), nullable=False))
        batch_op.drop_column('storage_loc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_loc', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('storage_location')

    # ### end Alembic commands ###
