"""empty message

Revision ID: c8a06106de8d
Revises: 8ba084108564
Create Date: 2024-06-10 16:41:33.197031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a06106de8d'
down_revision = '8ba084108564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('phone_num', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')
        batch_op.drop_column('address')
        batch_op.drop_column('phone_num')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
