"""empty message

Revision ID: d0a2f53cb61e
Revises: 18e464a1e8c3
Create Date: 2024-06-12 21:18:44.850352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a2f53cb61e'
down_revision = '18e464a1e8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_location', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_list', schema=None) as batch_op:
        batch_op.drop_column('storage_location')

    # ### end Alembic commands ###
