"""empty message

Revision ID: e94d64ba4ee5
Revises: 8e75acf66313
Create Date: 2024-06-08 20:33:22.602034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e94d64ba4ee5'
down_revision = '8e75acf66313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_list', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
